version: "3"
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: nibe_web
    container_name: nibe_web
    ports:
      - "8080:8080"
    volumes: 
      - ./:/app
    working_dir: "/app"
    links:
      - mongo
    command: sh -c 'swift run Run -e prod'

  frontend:
    container_name: nibe_frontend
    image: node:12.18-alpine
    volumes:
      - ./:/app
      - /app/frontend/node_modules
    working_dir: "/app/frontend"
    environment:
      - NODE_ENV=production
    command: sh -c 'yarn install && yarn build'

  editor:
    container_name: nibe_editor
    image: node:12.18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./editor:/app
      - /app/node_modules
    working_dir: "/app"
    depends_on:
      - web
    command: sh -c 'yarn install && yarn start'

  mongo:
    container_name: nibe_mongo
    image: mongo:4.0.10
    ports:
      - "27018:27017"
    volumes:
      - ${MONGO_DATA_DIR:-.mongo}:/data/db
